# Generated by Django 6.0.1 on 2026-01-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='thumbnail_url',
            new_name='thumbnail',
        ),
    ]
